#!/usr/bin/env ruby

APP_ROOT = File.dirname(__FILE__)
$:.unshift( APP_ROOT )

CONFIG_FILE_LOCATION = File.absolute_path(".obiconfig")

require 'obi/Controller'

delegate = Obi::Controller.new

Obi::Controller.start

# grab envioronment settings
# local = Obi::Environment.new.environment_settings("local")
# puts local[:name]