require 'mina/git'
# require 'mina/rollback'

set :repository, ENV['repo']
set :branch,     ENV['branch']

set :user,       ENV['user']
set :domain,     ENV['domain']
set :deploy_to,  ENV['path']

set :shared_paths, ['wp-content/uploads']
set :forward_agent, true

task :setup => :environment do

  queue! %[mkdir -p "#{deploy_to}/shared/wp-content/uploads"]

end

task :deploy => :environment do

  deploy do

    # Put things that will set up an empty directory into a fully set-up
    # instance of your project.
    invoke :'git:clone'
    invoke :'deploy:link_shared_paths'

  end
end

desc "Rollback to previous verison."

task :rollback => :environment do

    invoke :'deploy:rollback'

end
